services:
  scheduler-token:
    build:
      context: .
      target: scheduler-token
    restart: unless-stopped
    env_file:
      - env/common.env
      - env/cron-token.env

  scheduler-qoder:
    build:
      context: .
      target: scheduler-qoder
    restart: unless-stopped
    env_file:
      - env/common.env
      - env/cron-qoder.env
